# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-27 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170824_1102'),
        ('exercises', '0004_auto_20170802_1415'),
    ]

    operations = [
    ]
