# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170802_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession', verbose_name='WorkoutSession'),
        ),
    ]
